### ISSUE TITLE
zig master + http.zig dev not compiling due to websocket

### ISSUE THREAD

**Issue by kalapalo** [karlseguin/http.zig#162]
Is http.zig dev branch supposed to work with zig master (0.16.0) ?
When I try to build a little program I am doing that uses http.zig dev with zig master, I get an error on websocket, imported by src/http.zig, saying "src/proto.zig:100:48: error: root source file struct 'compress.flate' has no member named 'Decompressor' ".
It seems http.zig is importing an older version of websocket.zip, not the master one that is already using Io.
I have removed websocket from cache and zig fetched the master version, but it seems http.zig keep installing and using an older version.

**Comment by karlseguin** [comment]
It should, but I'm a bit behind. The changes have been hard to keep up with. I'll spend some time this weekend to try to get them caught up with zig master.

**Comment by karlseguin** [comment]
the `dev` branch should be working for `0.16.0-dev.427+86077fe6b`

**Comment by ezzieyguywuf** [comment]
broken on my linux box:

```
🕙 Sep 29 02:37:57.182 PM UTC-0400 wolfgangsanyer ~/Program/http.zig
❯ ../zig/zig-out/bin/zig version
0.16.0-dev.427+86077fe6b
🕙 Sep 29 02:38:14.485 PM UTC-0400 wolfgangsanyer ~/Program/http.zig
❯ ../zig/zig-out/bin/zig build test
Segmentation fault at address 0xffffffffffffff40
/home/wolfgangsanyer/Program/zig/zig-out/lib/zig/std/debug.zig:945:52: 0x11b90a2 in next_internal (std.zig)
        const new_fp = math.add(usize, @as(*usize, @ptrFromInt(fp)).*, fp_bias) catch
                                                   ^
/home/wolfgangsanyer/Program/zig/zig-out/lib/zig/std/debug.zig:868:39: 0x1165611 in next (std.zig)
        var address = it.next_internal() orelse return null;
                                      ^
/home/wolfgangsanyer/Program/zig/zig-out/lib/zig/std/debug.zig:507:29: 0x1102168 in captureStackTrace (std.zig)
            addr.* = it.next() orelse {
                            ^
/home/wolfgangsanyer/Program/zig/zig-out/lib/zig/std/heap/debug_allocator.zig:515:40: 0x1164c34 in collectStackTrace (std.zig)
            std.debug.captureStackTrace(first_trace_addr, &stack_trace);
                                       ^
/home/wolfgangsanyer/Program/zig/zig-out/lib/zig/std/heap/debug_allocator.zig:333:34: 0x10fefe0 in captureStackTrace (std.zig)
                collectStackTrace(ret_addr, stack_addresses);
                                 ^
/home/wolfgangsanyer/Program/zig/zig-out/lib/zig/std/heap/debug_allocator.zig:801:41: 0x10dbc1b in alloc (std.zig)
                bucket.captureStackTrace(ret_addr, slot_count, 0, .alloc);
                                        ^
/home/wolfgangsanyer/Program/zig/zig-out/lib/zig/std/mem/Allocator.zig:142:26: 0x10de481 in allocBytesWithAlignment__anon_6194 (std.zig)
    return a.vtable.alloc(a.ptr, len, alignment, ret_addr);
                         ^
/home/wolfgangsanyer/Program/zig/zig-out/lib/zig/std/mem/Allocator.zig:170:59: 0x118ddcc in create__anon_31711 (std.zig)
    const ptr: *T = @ptrCast(try a.allocBytesWithAlignment(.of(T), @sizeOf(T), @returnAddress()));
                                                          ^
/home/wolfgangsanyer/Program/http.zig/src/worker.zig:455:51: 0x112915a in init (httpz.zig)
            const websocket = try allocator.create(ws.Worker(WSH));
                                                  ^
/home/wolfgangsanyer/Program/http.zig/src/httpz.zig:430:49: 0x112b91e in listen (httpz.zig)
                    workers[i] = try Worker.init(allocator, self, &config);
                                                ^
/home/wolfgangsanyer/Program/zig/zig-out/lib/zig/std/Thread.zig:530:21: 0x112d5bc in callFn__anon_28627 (std.zig)
                    @call(.auto, f, args) catch |err| {
                    ^
/home/wolfgangsanyer/Program/zig/zig-out/lib/zig/std/Thread.zig:783:30: 0x10eef99 in entryFn (std.zig)
                return callFn(f, args_ptr.*);
                             ^
???:?:?: 0x7fc7e3ea1b7a in ??? (libc.so.6)
test
└─ run test failure
error: the following command terminated unexpectedly:
./.zig-cache/o/3d11d2f490b543734a96b980b21a3974/test

Build Summary: 3/5 steps succeeded; 1 failed
test transitive failure
└─ run test failure

error: the following build command failed with exit code 1:
.zig-cache/o/995a01a4ac5c627285c4781de536a1dc/build /home/wolfgangsanyer/Program/zig/zig-out/bin/zig /home/wolfgangsanyer/Program/zig/zig-out/lib/zig /home/wolfgangsanyer/Program/http.zig .zig-cache /home/wolfgangsanyer/.cache/zig --seed 0xa0b92465 -Z8415f56d8cf6c7ab test
🕙 Sep 29 02:38:28.685 PM UTC-0400 wolfgangsanyer ~/Program/http.zig
❯
```

I'll dig into it and see if I can find what's going on. I'll update here if I find anything

**Comment by ezzieyguywuf** [comment]
this was me trying to run httpz tests themselves
